"""make_user_full_name_non_nullable

Revision ID: 4d4dcad48d6b
Revises: 6301427ba51c
Create Date: 2026-04-16 21:36:36.737546

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d4dcad48d6b"
down_revision: str | Sequence[str] | None = "6301427ba51c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "full_name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "full_name", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
