"""add_cuil_to_users

Revision ID: 81f3e396c8cf
Revises: 84d06d592174
Create Date: 2026-04-19 19:37:41.529815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f3e396c8cf'
down_revision: Union[str, Sequence[str], None] = '84d06d592174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cuil', sa.CHAR(length=11), nullable=False))
    op.create_unique_constraint('uq_users_cuil', 'users', ['cuil'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_cuil', 'users', type_='unique')
    op.drop_column('users', 'cuil')
    # ### end Alembic commands ###
